Repository mash-up-kr/Nawa-Invitation-Web, pull requests merged in 2020-09, with the labels that each got.

#84 feat: #83. 템플릿 소개문구 추가
  src/api/invitationAPI.ts
  src/components/Invitation/Invitation.tsx
  src/models/Invitation.ts
Labels: enhancement

#79 파비콘 이미지 변경하기
  public/favicon.ico
  yarn.lock
Labels: bug

#85 feat: #76. 랜딩페이지 하단 멤버이름옆에 링크아이콘 추가
  src/assets/icons/link.svg
  src/components/Home/Home.module.scss
  src/components/Home/Home.tsx
  src/elements/SVGIcon/SVGIcon.tsx
  src/elements/SVGIcon/index.ts
Labels: enhancement

#78 애니매이션 변경 및 초대장 로딩 대기
  src/assets/invitation.json
  src/components/LoadingAnimation/LoadingAnimation.module.scss
  src/components/LoadingAnimation/LoadingAnimation.tsx
  src/components/LoadingAnimation/index.ts
  src/components/PopAnimation/index.ts
  src/containers/InvitationContainer.tsx
  src/pages/InvitationPage/InvitationPage.tsx
  src/redux/selectors/invitationSelector.ts
Labels: enhancement

#86 helmet 개선 및 og helmet 추가
  public/index.html
  src/App.tsx
  src/components/Error/Error.tsx
  src/components/Helmet/Helmet.tsx
  src/components/Helmet/index.ts
  src/components/Home/Home.tsx
  src/components/Invitation/Invitation.tsx
Labels: Improving, enhancement

#81 chore: #80. 초대장 요청 api의 쿼리파라미터로 타임스탬프 추가
  src/api/invitationAPI.ts
Labels: enhancement

#75 feat: #69. 초대장 footer추가
  src/App.tsx
  src/assets/images/app-download.png
  src/assets/images/get-more.png
  src/components/Invitation/Invitation.module.scss
  src/components/Invitation/Invitation.tsx
  src/components/ScrollToTop/ScrollToTop.tsx
  src/components/ScrollToTop/index.ts
Labels: enhancement

#88 Feedback v2.0
  package.json
  src/components/Error/Error.tsx
  src/components/Home/Home.module.scss
Labels: bug

#91 로딩애니매이션 duration 수정하기
  src/containers/InvitationContainer.tsx
Labels: Improving

#92 2차배포 피드백 반영
  src/assets/icons/app-download.svg
  src/assets/icons/get-more.svg
  src/assets/images/app-download.png
  src/assets/images/get-more.png
  src/components/Home/Home.module.scss
  src/components/Home/Home.tsx
  src/components/Invitation/Invitation.module.scss
  src/components/Invitation/Invitation.tsx
  src/containers/InvitationContainer.tsx
  src/elements/TextCarousel/TextCarousel.styled.ts
  src/redux/reducers/index.ts
  src/redux/selectors/commentSelector.ts
  src/redux/selectors/invitationSelector.ts
  src/utils/browserUtils.ts
Labels: Improving

#94 fix: #93. 임시로 위도 경도 바꿈
  src/components/Invitation/Invitation.tsx
  src/models/Map.ts
Labels: bug

#95 v2.1.0
  package.json
Labels: setting

#96 readme 파일 개선
  README.md
Labels: documentation

#101 feat: 채널톡 플러그인 추가
  src/App.tsx
  src/services/ChannelService.js
Labels: enhancement

#104 앱다운로드 링크 변경 및 preview개선
  src/App.tsx
  src/components/Home/Home.tsx
  src/components/Invitation/Invitation.tsx
  src/components/Preview/Preview.module.scss
  src/components/Preview/Preview.tsx
Labels: enhancement

#105 feat: 지도크기 동적으로 변하도록 개선
  src/assets/icons/squares-filled.svg
  src/assets/icons/squares.svg
  src/elements/Map/Map.styled.ts
  src/elements/Map/Map.tsx
  src/services/KakaoMapService.ts
Labels: enhancement

#108 feat: og태그 개선
  src/index.server.tsx
Labels: Improving

#110 fix: #109. 타임존 서울로 변경하여 시간 다르게 뜨던 버그 수정
  package.json
  src/utils/dateUtils.ts
Labels: bug
