Repository mash-up-kr/Nawa-Invitation-Web, pull requests merged in 2020-08, with the labels that each got.

#25 초대장 비동기액션 추가작성
  src/App.tsx
  src/api/invitationAPI.ts
  src/containers/InvitationContainer.tsx
  src/models/Invitation.ts
  src/pages/HomePage/HomePage.tsx
  src/redux/reducers/invitationReducer.ts
Labels: enhancement

#30 pr템플릿 수정
  .github/PULL_REQUEST_TEMPLATE.md
  .github/pull_request-template.md
Labels: documentation

#32 초대장 정보를 api를 통해 받아오는 요청로직 작성
  package-lock.json
  package.json
  src/api/invitationAPI.ts
  src/components/Comment/Comment.tsx
  src/components/Invitation/Invitation.module.scss
  src/components/Invitation/Invitation.tsx
  src/containers/InvitationContainer.tsx
  src/elements/KakaoMap/KakaoMap.styled.ts
  src/elements/KakaoMap/KakaoMap.tsx
  src/models/Invitation.ts
  src/models/KakaoMap.ts
  src/redux/reducers/invitationReducer.ts
  src/utils/dateUtils.ts
  src/utils/reduxUtils.ts
Labels: enhancement

#43 svg아이콘 src폴더 안으로 이동
  public/images/character.svg
  src/assets/icons/calendar.svg
  src/assets/icons/location.svg
  src/assets/icons/map.svg
  src/assets/icons/photo.svg
  src/assets/icons/time.svg
  src/assets/images/character.png
  src/components/Invitation/Invitation.module.scss
  src/components/Invitation/Invitation.tsx
  src/elements/SVGIcon/SVGIcon.styled.ts
  src/elements/SVGIcon/SVGIcon.tsx
  src/types/declaration.d.ts
Labels: Improving

#46 feat(!): #33. 초대장 미리보기 템플릿 작성
  public/preview/calendar.svg
  public/preview/character.png
  public/preview/index.css
  public/preview/index.html
  public/preview/location.svg
  public/preview/map.svg
  public/preview/photo.svg
  public/preview/time.svg
  src/components/Invitation/Invitation.module.scss
Labels: enhancement

#44 error페이지 작성 및 전역적으로 error handling하도록 구조작성
  public/index.html
  src/App.tsx
  src/assets/images/error_avatar.png
  src/components/Error/Error.module.scss
  src/components/Error/Error.tsx
  src/components/Error/index.ts
  src/components/ErrorHandler/ErrorHandler.tsx
  src/components/ErrorHandler/index.ts
  src/containers/InvitationContainer.tsx
  src/pages/ErrorPage/ErrorPage.module.scss
  src/pages/ErrorPage/ErrorPage.tsx
  src/pages/ErrorPage/index.ts
  src/pages/HomePage/HomePage.tsx
  src/pages/index.ts
  src/types/ErrorCodes.ts
Labels: enhancement

#53 refactor: no-useless-concat 해결
  src/serviceWorker.ts
Labels: bug

#49 feat: #35. customizing 된 애니매이션으로 변경, commitlint 추가
  package-lock.json
  package.json
  src/assets/fireworks.json
  src/assets/invitation.json
  src/components/PopAnimation/PopAnimation.tsx
  yarn.lock
Labels: enhancement

#52 feat: #31. 랜딩페이지 퍼블리싱
  src/App.tsx
  src/assets/images/homeImg/img_characterchoice.png
  src/assets/images/homeImg/img_chat.png
  src/assets/images/homeImg/img_inviteicon.png
  src/assets/images/homeImg/img_line.png
  src/assets/images/homeImg/img_logo.png
  src/assets/images/homeImg/img_main.png
  src/assets/images/homeImg/img_makeinvite.png
  src/assets/images/homeImg/img_onlineinvite.png
  src/assets/images/homeImg/img_reminder.png
  src/assets/img_logo.png
  src/components/Home/Home.module.scss
  src/components/Home/Home.tsx
  src/components/Home/index.ts
  src/pages/HomePage/HomePage.tsx
  src/pages/InvitationPage/InvitationPage.module.scss
  src/pages/InvitationPage/InvitationPage.tsx
  src/pages/InvitationPage/index.ts
  src/pages/index.ts
  src/styles/global-styles.ts
Labels: enhancement

#54 refactor: #27. 액션 크리에이터 개선
  package.json
  src/containers/InvitationContainer.tsx
  src/redux/middlewares/.gitkeep
  src/redux/middlewares/actionLifeCycles.ts
  src/redux/reducers/commentReducer.ts
  src/redux/reducers/invitationReducer.ts
  src/redux/reducers/todoReducer.ts
  src/redux/reduxStore.ts
  src/utils/reduxUtils.ts
Labels: refactoring

#71 chore: #70. 서버 도메인 변경에 따른 proxy재설정
  package.json
Labels: setting

#73 카카오맵으로 이동기능 추가
  package-lock.json
  package.json
  src/components/Invitation/Invitation.tsx
  src/services/UserAgentService.ts
Labels: enhancement
