Repository mash-up-kr/Nawa-Invitation-Web, pull requests merged in 2020-10, with the labels that each got.

#113 feat: #97. 초대장 이미지 보여주기 기능 추가
  src/api/invitationAPI.ts
  src/assets/icons/image.svg
  src/components/Invitation/Invitation.module.scss
  src/components/Invitation/Invitation.tsx
  src/models/Image.ts
  src/models/Invitation.ts
Labels: enhancement

#112 feat: #111. 지도에서 스크롤막기
  src/elements/Map/Map.tsx
Labels: enhancement

#114 댓글기능 추가
  src/App.tsx
  src/api/commentAPI.ts
  src/assets/icons/close.svg
  src/components/Comment/Comment.module.scss
  src/components/Comment/Comment.tsx
  src/components/CommentList/CommentList.module.scss
  src/components/CommentList/CommentList.tsx
  src/components/Invitation/Invitation.module.scss
  src/components/Invitation/Invitation.tsx
  src/containers/CommentListContainer.tsx
  src/containers/InvitationContainer.tsx
  src/models/Comment.ts
  src/modules/reducers/commentReducer.ts
  src/modules/selectors/commentSelector.ts
  src/pages/CommentPage/CommentPage.tsx
  src/pages/CommentPage/index.ts
  src/pages/index.ts
  src/utils/dateUtils.ts
Labels: bug, enhancement

#115 toList 제거, 디자인 수정
  src/components/CommentList/CommentList.module.scss
  src/components/CommentList/CommentList.tsx
Labels: bug

#116 버그 해결
  src/components/CommentList/CommentList.module.scss
Labels: bug
